[package]
name = "session-manager"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = "1.0.181"
serde_json = "1.0.113"
open = "5.0.0"
tokio = { version = "1.32.0", features = ["full"] }
sniffer-rs = "1.1.1"
whiskers-launcher-core = "0.3.0"
